# Site settings
title: "Exploration Log"
description: > 
  Notes on explorations on various topics of interest

author: Edwin Tunggawan
email: vcc.edwint@gmail.com
twitter_username: sdsdkkk
github_username: sdsdkkk

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sdsdkkk.github.io" # the base hostname & protocol for your site

google_analytics_id:
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

